name: task_management
description: Project task management.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.8.1
  country_picker: ^2.0.20
  dynamic_color: ^1.6.5
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  flutter:
    sdk: flutter
  flutter_datetime_picker_plus: ^2.0.1
  flutter_screenutil: ^5.8.4
  font_awesome_flutter: ^10.4.0
  google_fonts: ^5.1.0
  hooks_riverpod: ^2.3.6
  pinput: ^2.2.31
  riverpod_annotation: ^2.1.1
  sqflite: ^2.2.8+4

dev_dependencies:
  build_runner: ^2.4.5
  custom_lint: ^0.4.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
